# Generated by Django 3.2.7 on 2022-07-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='image',
            field=models.ImageField(blank=True, default='avatar.svg', null=True, upload_to='users/'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, to='users.Skill'),
        ),
    ]
