# Generated by Django 3.2.7 on 2022-07-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220712_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='user_type',
            field=models.CharField(choices=[('teach', 'Teacher'), ('stu', 'Student'), ('both', 'Both')], max_length=200),
        ),
    ]
