# Generated by Django 3.2.7 on 2022-07-15 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_skill_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profiles',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
    ]
