# Generated by Django 3.2.7 on 2022-07-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profiles_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='short_intro',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
