# Generated by Django 3.2.7 on 2022-07-17 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='twitter_link',
        ),
    ]
