# Generated by Django 3.2.7 on 2022-07-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20220717_0350'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=2000, null=True)),
                ('phone', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('about_us', models.TextField(blank=True, null=True)),
                ('copy_right', models.CharField(blank=True, max_length=200, null=True)),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='site_log/')),
            ],
        ),
    ]
