# Generated by Django 3.2.7 on 2022-07-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='student',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
