# Generated by Django 3.2.7 on 2022-07-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20220713_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='content',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
