# Generated by Django 3.2.7 on 2022-07-15 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_videos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videos',
            options={'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
    ]
