# Generated by Django 3.2.14 on 2022-08-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
